name: eeg-decoder
channels:
  - defaults
  - pytorch
  - conda-forge
  # - pyg
dependencies:
  - python=3.11
  - pip
  # - gcc==12.1.0
  # - pytorch-sparse
  - pip:
    - torch
    - torchvision
    - numpy
    - tqdm
    - pillow
    - scikit-image 
    - matplotlib
    - einops
    - transformers
    - pillow
    - mne
    - pandas  
    - scikit-learn
    - torch-geometric
    # - protobuf==3.20
    # - torch-scatter
    # - lightning
