program: NICE-EEG-main/nice_stand.py
command:                     # anything *not* swept stays fixed
  - ${env}
  - python
  - ${program}
  - --dataset_path
  - /scratch-shared/scur0549/datasets/Things-EEG2/
  - --use_attn
  - --image_features_type
  - hidden_states

method: bayes                # or "random", "grid", "asha"
metric:
  name: val/loss             # minimise validation loss
  goal: minimize

parameters:
  lr:
    distribution: log_uniform_values
    min: 1e-8
    max: 1e-4
  proj_dim:
    values: [128, 512, 768, 1024]
  att_heads:
    values: [2, 4, 8]
  att_blocks:
    values: [1, 2, 3]
  att_dropout:
    distribution: uniform
    min: 0.1
    max: 0.7

early_terminate:
  type: hyperband
  s: 2  
  eta: 3
  max_iter: 27