program: NICE-EEG-main/nice_stand.py
command:                     # anything *not* swept stays fixed
  - ${env}
  - python
  - ${program}
  - --dataset_path
  - /scratch-shared/scur0549/datasets/Things-EEG2/
  - --use_image_projector
  - --config
  - none
  - --eeg_patch_encoder 
  - multiscale
  - --small_run

method: bayes                # or "random", "grid", "asha"
metric:
  name: val/loss             # minimise validation loss
  goal: minimize

parameters:
  lr:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-3
  mstc_out_channels:
    values: [20, 32, 40, 50]
  mstc_kernel_sizes:
    values: ["3,11,25", "3,15,21", "3,15,25", "3,11,15"]
  mstc_dilation_rates:
    values: ["1,1,2", "1,2,2", "1,3,3", "1,1,1", "1,2,3"]
  mstc_pool_kernel_size:
    values: ["1,51", "1,45", "1,35"]
  mstc_pool_stride:
    values: ["1,5", "1,10", "1,15"]
  mstc_dropout_p:
    distribution: uniform
    min: 0.1
    max: 0.3
  pe_dropout_p:
    distribution: uniform
    min: 0.1
    max: 0.4

early_terminate:
  type: hyperband
  s: 2  
  eta: 3
  max_iter: 27